Add reviews
Canoutis/java-filmorate pull request #11
Opened 2023-06-08 20:05 UTC by noir74y

2023-06-08 20:33 UTC, Canoutis requested changes

2023-06-08 20:33 UTC, Canoutis commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDaoImpl.java
> +        setUseful(reviewId,0);
Можно избавиться от инициализации reviewId, если использовать примитивный тип

2023-06-08 20:33 UTC, Canoutis commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDaoImpl.java
> +        sqlQuery = "update review set content = ?, is_positive = ? where review_id = ?";
Добавим проверку что меняет юзер-создатель комментария, наверное это бизнес-требование

2023-06-09 14:52 UTC, noir74y commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDaoImpl.java
> +        setUseful(reviewId,0);
fixed

2023-06-09 14:59 UTC, noir74y commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDaoImpl.java
> +        sqlQuery = "update review set content = ?, is_positive = ? where review_id = ?";
посмотрел тесты постмана - там есть кейс, когда в отзыве меняются и userId, и filmId. Получается, для слоя бизнес-логики такая ситуация валидная.

2023-06-09 15:49 UTC, Canoutis approved these changes

2023-06-09 16:30 UTC, glebchik1995 approved these changes

2023-06-09 16:32 UTC, merged