added search
Canoutis/java-filmorate pull request #20
Opened 2023-06-10 10:36 UTC by v01cecrack

2023-06-10 11:04 UTC, Canoutis requested changes

2023-06-10 11:04 UTC, Canoutis commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +import java.util.*;
Будет классно если в Idea отключишь группировку импортов.

2023-06-10 11:04 UTC, Canoutis commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +import java.util.*;
То же самое, будет классно, если отключишь схлопывание

2023-06-10 11:04 UTC, Canoutis commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String param = "%" + query.toLowerCase() + "%";
А зачем яву заставлять еще несколько операций делать, может стоит сразу запрос в нижний регистр перевести, есть комбинация.  В мак shift+command+U - меняет регистр выбранного текста

2023-06-10 11:04 UTC, Canoutis commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql = "SELECT * FROM FILM WHERE LOWER(NAME) LIKE ?";
А что по рейтингу, как рейтинг в таком случае будет получаться? Может сделаем сразу в sql join чтобы бд нам сразу с рейтингом ответ выдал?

2023-06-10 11:04 UTC, Canoutis commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        List<Film> films = jdbcTemplate.query(sql, (rs, rowNum) -> filmMapper(rs), param);
Нам придется избавиться от маппера, в пользу комментария сверху, каждый раз за каждым фильмом ходить в базу чтобы получить рейтинг, который join-ом можно получить за первый запрос.

2023-06-13 20:33 UTC, glebchik1995 approved these changes

2023-06-13 20:41 UTC, v01cecrack commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +import java.util.*;
ok

2023-06-13 20:48 UTC, noir74y approved these changes

2023-06-13 21:09 UTC, Canoutis approved these changes

2023-06-13 21:09 UTC, merged