add-director
Canoutis/java-filmorate pull request #8
Opened 2023-06-08 15:47 UTC by Canoutis

2023-06-08 21:24 UTC, noir74y requested changes

2023-06-08 21:24 UTC, noir74y commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +public class DirectorController {
можно добавить @RequestMapping("/derictors") перед телом класса

2023-06-08 21:24 UTC, noir74y commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    @Autowired
в текущей версии спринга достаточно указать @RequiredArgsConstructor , он сам будет делать @Autowired

2023-06-08 21:24 UTC, noir74y commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        Optional<Director> createdDirector = directorDao.update(director);
rename to updateDirector

2023-06-08 21:24 UTC, noir74y commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDaoImpl.java
> +    static Director makeDirector(ResultSet rs, int rowNum) throws SQLException {
можно сделать non static

2023-06-08 21:24 UTC, noir74y commented on src/main/java/ru/yandex/practicum/filmorate/storage/director/DirectorDaoImpl.java
> +                "name = ?";
добавить "where = ?"

2023-06-08 21:41 UTC, Canoutis commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    @Autowired
Тут у нас возникли сомнения, оставим компромиссный вариант

2023-06-09 17:17 UTC, glebchik1995 approved these changes

2023-06-09 17:28 UTC, glebchik1995 approved these changes

2023-06-09 17:31 UTC, noir74y approved these changes

2023-06-09 17:31 UTC, merged